### ISSUE TITLE
Left mouse button support on kde

### ISSUE THREAD

**Issue by jinzhongjia** [dmikushin/tray#16]
May I ask, can this library support this function?
I checked several libraries, and none of them did not realize the support of the left mouse button.

**Comment by dmikushin** [comment]
Hi @jinzhongjia , I assume you have tested tray for KDE? If you did, kindly please share an answer to your own question. Also, if possible, please kindly contribute a screenshot of KDE similar to the other screenshots that we have! :pray:

**Comment by jinzhongjia** [comment]
Well, I've switched back to windows now, so I can't provide screenshots of kde now.

**Comment by dmikushin** [comment]
OK, just in case you return to KDE anytime later, please keep this request in mind.

**Comment by dmikushin** [comment]
I don't use KDE myself, but others do, so sharing your experience is very valuable!

**Comment by jinzhongjia** [comment]
Great, now left-click support is complete

**Comment by jinzhongjia** [comment]
![image](https://github.com/user-attachments/assets/0b263357-f652-4cf6-a77d-7b0804fc4d04)

**Comment by jinzhongjia** [comment]
I believe this screenshot is enough

**Comment by jinzhongjia** [comment]
But the quit in the example seems to be set to checkbox, but this is a minor problem.

**Comment by dmikushin** [comment]
Hi @jinzhongjia , thank you very much for your contribution, I've pushed your screenshot here: https://github.com/dmikushin/tray/commit/9db55bd7a8130b931025b8485c7887e1a989dd56

**Comment by jinzhongjia** [comment]
> But the quit in the example seems to be set to checkbox, but this is a minor problem.

Oh, this seems to be a bug, all text is rendered as a checkbox, under kde

**Comment by dmikushin** [comment]
Yes, this is not what we intend.
